{
 "title": "BeatSaber",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "ScoreSaber", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Score",
   "type": "stat",
   "description": "Your Total Score on ScoreSaber\n",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scoresaber_total_score", "legendFormat": "Total Score" }
   ]
  },
  {
   "title": "Global Rank",
   "type": "graph",
   "description": "Your current Global Rank on ScoreSaber\n",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    { "expr": "scoresaber_rank", "legendFormat": "Global Rank" }
   ]
  },
  {
   "title": "ScoreSaber PP",
   "type": "graph",
   "description": "Your current PP on ScoreSaber\n",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "scoresaber_pp", "legendFormat": "Current PP" }
   ]
  },
  {
   "title": "Ranked Score",
   "type": "stat",
   "description": "Your Total Ranked Score on ScoreSaber\n",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scoresaber_total_ranked_score", "legendFormat": "Total Ranked Score" }
   ]
  },
  {
   "title": "Play Count",
   "type": "stat",
   "description": "Your Total Play Count on ScoreSaber\n",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scoresaber_total_play_count", "legendFormat": "Total Play Count" }
   ]
  },
  {
   "title": "Ranked Play Count",
   "type": "stat",
   "description": "Your Total Ranked Play Count on ScoreSaber\n",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scoresaber_ranked_play_count", "legendFormat": "Total Ranked Score" }
   ]
  },
  {
   "title": "Country Rank",
   "type": "graph",
   "description": "Your current Country Rank on ScoreSaber\n",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "scoresaber_country_rank", "legendFormat": "Country Rank" }
   ]
  },
  {
   "title": "Average Ranked Accuracy",
   "type": "timeseries",
   "description": "Your Average Ranked Accuracy on ScoreSaber",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "scoresaber_average_ranked_accuracy",
     "legendFormat": "Average Ranked Accuracy"
    }
   ]
  },
  {
   "title": "Replays Watched",
   "type": "stat",
   "description": "Your Total Replays Watched by other players on ScoreSaber\n",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scoresaber_replays_watched", "legendFormat": "Total Ranked Score" }
   ]
  }
 ]
}